package com.lzj.sync.dao;

import com.lzj.sync.entity.OrderEntity;
import com.lzj.sync.entity.OrderEntityExample;
import org.apache.ibatis.annotations.Mapper;

/**
 * OrderEntityMapper
 *
 * @author outpaces
 * @date 2019/11/6 18:53
 * @version 1.0
 */
@Mapper
public interface OrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    long countByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    int insert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    int insertSelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    OrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderEntity record);
}