package com.lzj.sync.entity;

import com.lzj.sync.data.AbstractEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * 订单实体
 *
 * @author outpaces
 * @date 2019/11/4 21:56
 * @version 1.0
 */
@EqualsAndHashCode(callSuper = true)
@Data
public class OrderEntity extends AbstractEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.productCode
     *
     * @mbg.generated
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    public OrderEntity(Long id, String userId, String productCode, Integer quantity) {
        this.id = id;
        this.userid = userId;
        this.productcode = productCode;
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    public OrderEntity() {
        super();
    }
}