spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.162:3306/order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8080
rabbitmq:
  produce:
    all:
      host: 192.168.71.162
      port: 5672
      userName: guest
      password: guest
      virtualHost: test
      queueName: queue_order_all
      exchange: exchange_order_all
      routingKey: route_key_order_all
      acknowledgeMode: manual
      publisherConfirms: true
      publisherReturns: true
    increment:
      host: 192.168.71.162
      port: 5672
      userName: guest
      password: guest
      virtualHost: test
      queueName: queue_order_increment
      exchange: exchange_order_increment
      routingKey: route_key_order_increment
      acknowledgeMode: manual
      publisherConfirms: true
      publisherReturns: true
  consume:
    increment:
      host: 192.168.71.162
      port: 5672
      userName: guest
      password: guest
      virtualHost: test
      queueName: queue_order_consume_increment
      exchange: exchange_order_consume
      routingKey: route_key_order_consume_increment
      acknowledgeMode: manual
      publisherConfirms: false
      publisherReturns: false
mybatis:
 mapper-locations:
  - classpath:mapper/*.xml